### ISSUE TITLE
Initital Project Plan

### ISSUE THREAD

**Issue by pat-bert** [pat-bert/BatteryManagementSystem#32]
- [x] Initital set of tasks as issues

- [x] Group issues by subject into epics

- [x] Estimate complexity of issues

- [x] Assign issues to the first sprint (bi-weekly time period)
